Lesson 8
RDesukevich/if-html pull request #7
Opened 2021-08-10 21:22 UTC by RDesukevich

2021-08-11 21:07 UTC, Dronom requested changes

2021-08-11 21:07 UTC, Dronom commented on Landing CV/index.html
> +            </article>
it should be done as img)
images can be icons and stars. everything else should be written by code.
Also use different alt for all skils

2021-08-15 22:27 UTC, Dronom approved these changes

2021-08-15 22:27 UTC, Dronom commented on Landing CV/index.html
> +            <article class="row">
bad naming

2021-08-15 22:50 UTC, RDesukevich commented on Landing CV/index.html
> +            <article class="row">
А что именно?

2021-08-22 23:52 UTC, Dronom commented on Landing CV/index.html
> +            <article class="row">
из класса row непонятно какой это элемент, к какой секции он относится

2021-08-22 23:55 UTC, Dronom commented on Landing CV/index.html
> +            <article class="row">
чуть ниже используется `suggestions__col`, можно по аналогии назвать `suggestions__row`

2021-10-01 08:34 UTC, merged